# Generated by Django 4.2.16 on 2024-10-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='participants',
            new_name='members',
        ),
    ]
